[tool.poetry]
name = "canais_navegacao"
version = "0.1.0"
description = "Ferramenta computacional para análise e pré-dimensionamento de canais de navegação em águas rasas."
authors = ["Bruno Carlotto Rezende"]
license = "MIT"
readme = "README.md"
packages = [{ include = "canais_navegacao", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"

[tool.poetry.group.dev.dependencies]
pytest = ">=8,<9"
ipykernel = ">=6,<7"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

